defaults:
  - model: llae
  - training: ae
  - data: combustion
  - eval: default
  - _self_

seed: 42
project: convdiff
save_dir: /Data/KAT/checkpoints

hydra:
  run:
    dir: .
  output_subdir: .log/.hydra
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        formatter: simple
        filename: .log/${hydra.job.name}.log
        mode: w
